using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StrategyMortal : MonoBehaviour
{
    public enum Strategy
    {
        /* De : 1 Mortal [2,2] */ De ,
        /* Be : 2 Mortal [2,2] */ Be ,
        /* Ge : 3 Mortal [2,2] */ Ge ,
        /* Re : 4 Mortal [2,2] */ Re ,
        /* Te : 5 Mortal [3,2] */ Te ,
        /* Se : 6 Mortal [2,2] */ Se ,
        /* UE : 7 Mortal [2,2] */ UE ,
        /* Je : 8 Mortal [2,2] */ Je ,
        /* Pe : 9 Mortal [2,2] */ Pe ,
        /* Oe : 10 Mortal [2,2] */ Oe ,
        /* Le : 11 Mortal [2,2] */ Le ,
        /* We : 12 Mortal [2,2] */ We ,
        /* He : 13 Mortal [2,2] */ He ,
        /* Qe : 14 Mortal [2,2] */ Qe ,
        /* AE : 15 Mortal [2,2] */ Ae ,
        /* Ke : 16 Mortal [2,2] */ Ke ,
        /* ME : 17 Mortal [2,2] */ ME ,
        /* CE : 18 Mortal [2,2] */ CE ,
        /* CE : 19 Mortal [2,2] */ NE ,
        /* CE : 20 Mortal [2,2] */ VE ,
        /* NO INFO */ PPE ,
        CCE ,
        BBE ,
        OOE ,
        UUE ,
        JJE , 
        GGE , 
        RRE ,
        FFE , 
        TTE ,
        AAE , 
        QQE , 
        VVE , 
        WWE ,
        SSE , 
        ZZE ,
        YYE ,
        DDE , 
        MME , 
        LLE ,
        IIE ,
        NNE ,
        XXE , 
        KKE ,
        HHE ,
        EEE , 
        WEE ,
        KYE ,
        QUE ,
        BNE ,
        GTE , 
        BRE ,
        KHE ,
        QGE ,
        ZEE ,
        MKE ,
        BTE ,
        YYYE ,
        OKRE ,
        HGRE ,
        HBGE ,
        AZDE ,
        BBBE ,
        BGRE ,
        PERE ,
        FFFE ,
        DDDE ,
        KMHE ,
        End1,
        End2,
        End3,
        End4,
        End5,
        End6,
        End7,
        End8,
        End9,
        End10,
        End11,
        End12,
        End13,
        End14,
        End15,
        End16,
        End17,
        End18,
        End19,
        End20,
        End21,
        End22,
        End23,
        End24,
        End25,
        End26,
        End27,
        End28,
        End29,
        End30,
        End31,
        End32,
        End33,
        End34,
        End35,
        End36,
        End37,
        End38,
        End39,
        End40,
        End41,
        End42,
        End43,
        End44,
        End45,
        End46,
        End47,
        End48,
        End49,
        End50,
        End51,
        End52,
        End53,
        End54,
        End55,
        End56,
        End57,
        End58,
        End59,
        End60,
        End61,
        End62,
        End63,
        End64,
        End65,
        End66,
        End67,
        End68,
        End69,
        End70,
        End71,
        End72,
        End73,
        End74,
        End75,
        End76,
        End77,
        End78,
        End79,
        End80,
        End81,
        End82,
        End83,
        End84,
        End85,
        End86,
        End87,
        End88,
        End89,
        End90,
        End91,
        End92,
        End93,
        End94,
        End95,
        End96,
        End97,
        End98,
        End99,
        End100,
    }
}
